// <auto-generated />
using System;
using ExamSimulator.Web.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamSimulator.Web.Infrastructure.Migrations
{
    [DbContext(typeof(ExamSimulatorDbContext))]
    partial class ExamSimulatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ExamSimulator.Web.Domain.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CorrectOptionIndex");

                    b.Property<string>("ExamProfileId")
                        .IsRequired();

                    b.Property<string>("Options")
                        .IsRequired();

                    b.Property<string>("Prompt")
                        .IsRequired();

                    b.Property<string>("TopicTag")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Questions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
